webtalk_init -webtalk_dir C:/Users/alexr/ECE449Main/ECE449Main.sim/sim_1/behav/xsim/xsim.dir/ALUTest_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Feb 17 17:56:14 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "c21b998f-99db-477f-b1e9-58c891e8f32e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bd56acb4f8004fa8831a86f65c5f783c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "45" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 7900X3D 12-Core Processor          " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "4400 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7844_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2708074344 -regid "" -xml C:/Users/alexr/ECE449Main/ECE449Main.sim/sim_1/behav/xsim/xsim.dir/ALUTest_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/alexr/ECE449Main/ECE449Main.sim/sim_1/behav/xsim/xsim.dir/ALUTest_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/alexr/ECE449Main/ECE449Main.sim/sim_1/behav/xsim/xsim.dir/ALUTest_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
